# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hitseekpy',
                'doc_host': 'https://davegrays.github.io',
                'git_url': 'https://github.com/davegrays/hitseekpy',
                'lib_path': 'hitseekpy'},
  'syms': { 'hitseekpy.core': {'hitseekpy.core.foo': ('core.html#foo', 'hitseekpy/core.py')},
            'hitseekpy.proc': {},
            'hitseekpy.scores': { 'hitseekpy.scores._plate_idx_to_flat': ('scores.html#_plate_idx_to_flat', 'hitseekpy/scores.py'),
                                  'hitseekpy.scores.get_b_scores': ('scores.html#get_b_scores', 'hitseekpy/scores.py'),
                                  'hitseekpy.scores.get_npis': ('scores.html#get_npis', 'hitseekpy/scores.py'),
                                  'hitseekpy.scores.get_percentages_of_controls': ( 'scores.html#get_percentages_of_controls',
                                                                                    'hitseekpy/scores.py'),
                                  'hitseekpy.scores.get_ssmd': ('scores.html#get_ssmd', 'hitseekpy/scores.py'),
                                  'hitseekpy.scores.get_z_scores': ('scores.html#get_z_scores', 'hitseekpy/scores.py')}}}
